package org.softwareanvil.ui

enum class Screen {
    HOME,
    GENERATE_MENU,
    GENERATE_COUNTRIES,
    GENERATE_CHARACTERS,

    LIBRARY_MENU,
    COUNTRY_LIBRARY,
    CHARACTER_LIBRARY,
    
    COUNTRY_DETAIL,
    CHARACTER_DETAIL
}